question_data = [
    {
        "category":"Entertainment: Video Games",
        "type":"boolean",
        "difficulty":"medium",
        "question":"Amazon acquired Twitch in August 2014 for $970 million dollars.",
        "correct_answer":"True",
        "incorrect_answers":["False"]},
    {
        "category":"Entertainment: Video Games",
        "type":"boolean",
        "difficulty":"medium",
        "question":"Super Mario Bros. was released in 1990.",
        "correct_answer":"False",
        "incorrect_answers":["True"]},
    {"category":"Entertainment: Video Games",
        "type":"multiple",
        "difficulty":"easy",
        "question":"Who is the writer of the game &quot;Half-Life&quot;?",
        "correct_answer":"Marc Laidlaw",
        "incorrect_answers":["Gabe Newell","Robin Walker","Chet Faliszek"]},
    {
        "category":"Entertainment: Video Games",
        "type":"multiple",
        "difficulty":"hard",
        "question":"Which video game was recalled for containing a hidden, playable South Park episode?",
        "correct_answer":"Tiger Woods 99 PGA Tour",
        "incorrect_answers":["Tony Hawk&#039;s Pro Skater 3","Sonic Adventure","Madden 99"]},
    {
        "category":"Entertainment: Video Games",
        "type":"multiple",
        "difficulty":"medium",
        "question":"What is the name the location-based augmented reality game developed by Niantic before Pok&eacute;mon GO?",
        "correct_answer":"Ingress",
        "incorrect_answers":["Aggress","Regress","Digress"]},
    {
        "category":"Entertainment: Video Games",
        "type":"multiple",
        "difficulty":"easy",
        "question":"In the first game of the Sly Cooper franchise, what family heirloom did Sly Cooper want to steal back?",
        "correct_answer":"Thievius Raccoonus",
        "incorrect_answers":["Raccoon Training 101","The Art of Sneak","Raccoonus Teachus"]},
    {
        "category":"Entertainment: Video Games",
        "type":"boolean",
        "difficulty":"easy",
        "question":"The 2005 video game &quot;Call of Duty 2: Big Red One&quot; is not available on PC.",
        "correct_answer":"True",
        "incorrect_answers":["False"]},
    {
        "category":"Entertainment: Video Games",
        "type":"multiple",
        "difficulty":"hard",
        "question":"How long was the World Record Speed Run of Valve Software&#039;s &quot;Half-Life&quot; that was done in 2014.",
        "correct_answer":"20 Minutes, 41 Seconds",
        "incorrect_answers":["45 Minutes, 32 Seconds","5 Minutes, 50 Seconds","12 Minutes, 59 Seconds"]},
    {
        "category":"Entertainment: Video Games",
        "type":"multiple",
        "difficulty":"medium",
        "question":"In WarioWare: Smooth Moves, which one of these is NOT a Form?",
        "correct_answer":"The Hotshot",
        "incorrect_answers":["The Discard","The Elephant","The Mohawk"]},
    {
        "category":"Entertainment: Video Games",
        "type":"multiple",
        "difficulty":"easy",
        "question":"Which of the following names is the &quot;Mega Man&quot; Franchise known as in Japan?",
        "correct_answer":"Rockman",
        "incorrect_answers":["Paperman","Scissorsman","Mega Man"]},
    ]